-- ANIMOA V2.4.0 — activation du questionnaire public
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.animoa_survey_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  animals text[] not null,
  other_animal text,
  current_method text not null,
  useful_features text[] not null,
  testing_interest text not null,
  email text,
  desired_use text,
  source text not null default 'animoa.fr',
  constraint animoa_survey_animals_required check (cardinality(animals) between 1 and 8),
  constraint animoa_survey_features_required check (cardinality(useful_features) between 1 and 12),
  constraint animoa_survey_interest_valid check (testing_interest in ('Oui', 'Peut-être', 'Non')),
  constraint animoa_survey_email_required check (testing_interest = 'Non' or email is not null),
  constraint animoa_survey_other_length check (other_animal is null or char_length(other_animal) <= 80),
  constraint animoa_survey_email_length check (email is null or char_length(email) <= 160),
  constraint animoa_survey_desired_length check (desired_use is null or char_length(desired_use) <= 300)
);

alter table public.animoa_survey_responses enable row level security;

revoke all on public.animoa_survey_responses from anon, authenticated;
grant insert on public.animoa_survey_responses to anon, authenticated;
grant usage, select on sequence public.animoa_survey_responses_id_seq to anon, authenticated;

drop policy if exists "Animoa envoyer questionnaire public" on public.animoa_survey_responses;
create policy "Animoa envoyer questionnaire public"
on public.animoa_survey_responses
for insert
to anon, authenticated
with check (
  cardinality(animals) between 1 and 8
  and cardinality(useful_features) between 1 and 12
  and testing_interest in ('Oui', 'Peut-être', 'Non')
  and (testing_interest = 'Non' or email is not null)
);

-- Aucune autorisation de lecture publique n'est accordée.
-- Les réponses restent consultables uniquement depuis le tableau de bord Supabase
-- ou avec un rôle serveur autorisé.
