-- ANIMOA 3.0 — Notifications Web Push

create table if not exists public.animoa_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_key text not null,
  user_agent text,
  timezone text not null default 'Europe/Paris',
  enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists animoa_push_subscriptions_user_idx
  on public.animoa_push_subscriptions(user_id, enabled);

create table if not exists public.animoa_push_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subscription_id uuid references public.animoa_push_subscriptions(id) on delete set null,
  notification_key text not null,
  category text not null check (category in ('appointment','vaccine','treatment','birthday','test','news')),
  title text not null,
  body text not null,
  status text not null default 'pending' check (status in ('pending','sent','failed','skipped')),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (subscription_id, notification_key)
);

create index if not exists animoa_push_deliveries_user_idx
  on public.animoa_push_deliveries(user_id, created_at desc);

alter table public.animoa_push_subscriptions enable row level security;
alter table public.animoa_push_deliveries enable row level security;

revoke all on public.animoa_push_subscriptions from anon;
revoke all on public.animoa_push_deliveries from anon;
grant select, insert, update, delete on public.animoa_push_subscriptions to authenticated;
grant select on public.animoa_push_deliveries to authenticated;
grant all on public.animoa_push_subscriptions, public.animoa_push_deliveries to service_role;
grant usage, select on sequence public.animoa_push_deliveries_id_seq to service_role;

drop policy if exists "Animoa push lire ses appareils" on public.animoa_push_subscriptions;
drop policy if exists "Animoa push ajouter son appareil" on public.animoa_push_subscriptions;
drop policy if exists "Animoa push modifier son appareil" on public.animoa_push_subscriptions;
drop policy if exists "Animoa push supprimer son appareil" on public.animoa_push_subscriptions;
drop policy if exists "Animoa push lire son historique" on public.animoa_push_deliveries;

create policy "Animoa push lire ses appareils"
on public.animoa_push_subscriptions for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Animoa push ajouter son appareil"
on public.animoa_push_subscriptions for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Animoa push modifier son appareil"
on public.animoa_push_subscriptions for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Animoa push supprimer son appareil"
on public.animoa_push_subscriptions for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "Animoa push lire son historique"
on public.animoa_push_deliveries for select to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.set_animoa_push_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists animoa_push_subscriptions_updated_at on public.animoa_push_subscriptions;
create trigger animoa_push_subscriptions_updated_at
before update on public.animoa_push_subscriptions
for each row execute function public.set_animoa_push_updated_at();

-- ANIMOA 3.10.0 — Planning versionné du répartiteur Web Push.
-- Ce planning utilise les mêmes secrets Vault que le script 03_rappels_24h.sql :
-- animoa_project_url et animoa_cron_secret.
create extension if not exists pg_cron;
create extension if not exists pg_net;

do $$
begin
  if exists (
    select 1 from cron.job
    where jobname = 'animoa-push-dispatch-hourly'
  ) then
    perform cron.unschedule('animoa-push-dispatch-hourly');
  end if;
end;
$$;

-- Exécution toutes les heures, à la minute 15.
-- La fonction accepte une fenêtre de 70 minutes, ce qui évite de manquer un rappel
-- en cas de léger retard du Cron.
select cron.schedule(
  'animoa-push-dispatch-hourly',
  '15 * * * *',
  $$
  select net.http_post(
    url := (
      select decrypted_secret
      from vault.decrypted_secrets
      where name = 'animoa_project_url'
    ) || '/functions/v1/animoa-push-dispatch',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-animoa-cron-secret', (
        select decrypted_secret
        from vault.decrypted_secrets
        where name = 'animoa_cron_secret'
      )
    ),
    body := jsonb_build_object(
      'source', 'supabase-cron',
      'requested_at', now()
    ),
    timeout_milliseconds := 20000
  );
  $$
);

select jobid, jobname, schedule, active
from cron.job
where jobname = 'animoa-push-dispatch-hourly';
